# Generated by Django 5.2 on 2025-06-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badges',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('req_XP', models.PositiveIntegerField()),
                ('picture_link', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
                'ordering': ['category'],
            },
        ),
    ]
