# Generated by Django 5.2 on 2025-06-11 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badges',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('req_XP', models.PositiveIntegerField()),
                ('picture_link', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Category name', max_length=100, unique=True)),
                ('description', models.TextField(help_text='Description of the category')),
                ('my_type', models.CharField(choices=[('EX1', 'Ex1'), ('EX2', 'Ex2'), ('EX3', 'Ex3')], max_length=10)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('points', models.PositiveIntegerField()),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('DIFFICULT', 'Difficult')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('link', 'Link'), ('text', 'Text')], max_length=10)),
                ('file', models.FileField(upload_to='quiz_resources/')),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('quiz_type', models.CharField(choices=[('MCQ', 'Multiple Choice Question'), ('SCQ', 'Single Choice Question'), ('TF', 'True or False')], max_length=10)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('points_awarded', models.IntegerField(default=0)),
                ('is_validated', models.BooleanField(default=False)),
                ('creator', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quizzes.category')),
                ('resources', models.ManyToManyField(related_name='resources', to='Quizzes.resource')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QuizBody',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('questions', models.ManyToManyField(related_name='questions', to='Quizzes.question')),
                ('quiz', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Quizzes.quiz')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(related_name='possible_answers', to='Quizzes.resource'),
        ),
        migrations.AddField(
            model_name='question',
            name='good_answers',
            field=models.ManyToManyField(related_name='good_answers', to='Quizzes.resource'),
        ),
    ]
