# Generated by Django 5.2 on 2025-06-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizzes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Badges',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['my_type'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['id'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='quizbody',
            options={'ordering': ['id'], 'verbose_name': 'QuizBody', 'verbose_name_plural': 'QuizBodies'},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['id'], 'verbose_name': 'Resource', 'verbose_name_plural': 'Resources'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='topic',
            field=models.CharField(default='General', help_text='Topic name', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('DIFFICULT', 'Difficult')], default='easy', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='content',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(help_text='Description of the topic'),
        ),
        migrations.AlterField(
            model_name='category',
            name='my_type',
            field=models.CharField(choices=[('VD', 'Vd'), ('CS', 'Cs'), ('AI', 'Ai')], max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='creator',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='points_awarded',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='quizbody',
            name='id',
            field=models.PositiveIntegerField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='quiz_resources/'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
