# Generated by Django 5.2 on 2025-06-11 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DesignNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', models.CharField(help_text='Background color in hexadecimal', max_length=7)),
                ('border_radius', models.PositiveIntegerField(help_text='Border radius in pixels')),
                ('display_duration', models.PositiveIntegerField(default=5, help_text='Notification display duration in seconds')),
            ],
        ),
        migrations.CreateModel(
            name='ImageElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(help_text='link to the image', max_length=128)),
                ('x_position', models.PositiveIntegerField(help_text='position on x abscissa')),
                ('y_position', models.PositiveIntegerField(help_text='position on y abscissa')),
                ('x_size', models.PositiveIntegerField(help_text='size on x abscissa')),
                ('y_size', models.PositiveIntegerField(help_text='size on y abscissa')),
                ('border_radius', models.PositiveIntegerField(default=0, help_text='image border radius in pixels')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('BOLD', 'Bold'), ('ITALIC', 'Italic'), ('UNDERLINED', 'Underlined'), ('BORDER', 'Border')], max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Text content')),
                ('color', models.CharField(help_text='Text color in hexadecimal', max_length=7)),
                ('font', models.CharField(help_text='Font name as string', max_length=30)),
                ('size', models.PositiveIntegerField(default=14, help_text='Font size in pixels')),
                ('alignement', models.CharField(choices=[('LEFT', 'Left'), ('CENTER', 'Center'), ('RIGHT', 'Right')], default='CENTER', max_length=10)),
                ('special_attributes', models.ManyToManyField(related_name='specials', to='Notifications.specialattributes')),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=64, unique=True)),
                ('sender', models.CharField(default='Anonymous', max_length=128)),
                ('receiver', models.CharField(default='Anonymous', max_length=128)),
                ('is_read', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='LOW', help_text='Define notification priority', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('design', models.ForeignKey(help_text='Design settings for a single notification', on_delete=django.db.models.deletion.CASCADE, to='Notifications.designnotification')),
                ('images', models.ManyToManyField(related_name='images', to='Notifications.imageelement')),
                ('content', models.ManyToManyField(related_name='contents', to='Notifications.text')),
            ],
        ),
    ]
