# Generated by Django 5.2 on 2025-06-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='designnotification',
            options={'verbose_name': 'DesignNotification', 'verbose_name_plural': 'DesignNotifications'},
        ),
        migrations.AlterModelOptions(
            name='imageelement',
            options={'ordering': ['id'], 'verbose_name': 'ImageElement', 'verbose_name_plural': 'ImageElements'},
        ),
        migrations.AlterModelOptions(
            name='notifications',
            options={'ordering': ['id'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterModelOptions(
            name='specialattributes',
            options={'verbose_name': 'SpecialAttribute', 'verbose_name_plural': 'SpecialAttributes'},
        ),
        migrations.AlterModelOptions(
            name='text',
            options={'ordering': ['id'], 'verbose_name': 'Text', 'verbose_name_plural': 'Texts'},
        ),
        migrations.AlterField(
            model_name='imageelement',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
