# Generated by Django 5.2 on 2025-06-18 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleQuiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squiz',
            name='category',
        ),
    ]
