# Generated by Django 5.2 on 2025-06-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleQuiz', '0002_remove_squiz_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squiz',
            name='difficulty',
            field=models.CharField(default='Easy', max_length=50),
        ),
    ]
