# Generated by Django 5.2 on 2025-06-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleQuiz', '0002_remove_squiz_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='squiz',
            name='description',
            field=models.TextField(default='No description available', max_length=520),
        ),
        migrations.AlterField(
            model_name='squiz',
            name='difficulty',
            field=models.CharField(default='Russian Roulette', max_length=50),
        ),
    ]
