# Generated by Django 5.2 on 2025-06-19 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleQuiz', '0003_alter_squiz_difficulty'),
        ('SimpleQuiz', '0003_squiz_description_alter_squiz_difficulty'),
    ]

    operations = [
    ]
