# Generated by Django 5.2 on 2025-05-10 02:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Achievements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_superadmin', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('player', 'Player'), ('admin', 'Admin')], default='admin', max_length=10)),
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Admins',
                'db_table': 'admin',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('level', models.PositiveIntegerField(default=0)),
                ('current_xp', models.PositiveIntegerField(default=0)),
                ('current_points', models.PositiveIntegerField(default=0)),
                ('login_streak', models.PositiveIntegerField(default=0)),
                ('login_count', models.PositiveIntegerField(default=0)),
                ('role', models.CharField(choices=[('player', 'Player'), ('admin', 'Admin')], default='player', max_length=10)),
                ('friends', models.ManyToManyField(blank=True, to='Users.player')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Achievements.rank')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Achievements.title')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
                'db_table': 'player',
                'ordering': ['created_at'],
            },
        ),
    ]
