# Generated by Django 5.2 on 2025-05-10 09:06

import Users.auth_models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Achievements', '0001_initial'),
        ('Users', '0002_alter_admin_id_alter_player_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='rank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Achievements.rank'),
        ),
        migrations.CreateModel(
            name='AdminAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=Users.auth_models.generate_uuid, unique=True)),
                ('access', models.CharField(max_length=40)),
                ('refresh', models.CharField(max_length=40, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Users.admin')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=Users.auth_models.generate_uuid, unique=True)),
                ('access', models.CharField(max_length=40)),
                ('refresh', models.CharField(max_length=40, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Users.player')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
