# Generated by Django 5.2 on 2025-06-11 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Achievements', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rank',
            old_name='nex_rank',
            new_name='next_rank',
        ),
    ]
